name: Release

on:
  release:
    types: [prereleased,released] 
    
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Tester
        run: |
          cd cli
          mkdir build
          bash build.sh

      - name: Build Monitor
        run: |
          cd monitor
          mkdir build
          bash build.sh
      
      - name: Upload Tester build
        run: |
          cd cli/build
          for file in *; do
            echo "Uploading $file"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/octet-stream" --data-binary "@$file" "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=$file"
          done
      
      - name: Upload Monitor build
        run: |
          cd monitor/build
          for file in *; do
            echo "Uploading $file"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/octet-stream" --data-binary "@$file" "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=$file"
          done
