name: Release

on:
  release:
    types: [edited,prereleased,released] 
    
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Tester
        run: |
          cd cli
          mkdir build
          bash build.sh

      - name: Build Monitor
        run: |
          cd monitor
          mkdir build
          bash build.sh
      
      - name: Upload Tester binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            ./cli/build/*
            ./monitor/build/*
          asset_content_type: application/octet-stream
